import '../lib/localStorage-polyfill';
import type { Metadata } from "next";
import { Geist_Mono, Poppins } from "next/font/google";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v16-appRouter';
import LayoutWrapper from '../components/layout/LayoutWrapper';
import ClientThemeProvider from '../providers/ThemeProvider';

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Xen.ai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistMono.variable} ${poppins.variable} antialiased`}>
        <AppRouterCacheProvider>
          <ClientThemeProvider>
            <LayoutWrapper>
              {children}
            </LayoutWrapper>
          </ClientThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html >
  );
}
