export enum ResponseValidationTypeEnum {
    UUID = "Uuid",
    STRING = "String",
    NUMBER = "Number",
    BOOLEAN = "Boolean",
    EMAIL = "Email",
    PHONE = "Phone",
    NO_SPECIAL_CHARACTERS = "NoSpecialCharacters",
    ENUM = "Enum",
    REQUIRED = "Required",
    LETTER_ONLY = "LetterOnly",
    NO_PROHIBITED_CHARACTERS = "NoProhibitedCharacters",
    KEYCLOAK_PROHIBITED_CHARACTERS = "KeycloakProhibitedCharacters",
    STRING_BOOLEAN_NUMERIC = "StringBooleanNumeric",
    STRING_DATE_FORMAT = "StringDateFormat",
    SHORT_STRING_DATE_FORMAT = "ShortStringDateFormat",
    STRING_OF_NUMBER_OR_FLOAT = "StringOfNumberOrFloat",
    STRING_OF_MAP_COORDINATE = "StringOfMapCoordinate",
    STRING_DATE_RANGE = "StringDateRange",
    DATE = "Date",
    DATE_ISO = "DateISO",
    DATE_ONLY = "date_only",
    MONTH_WITH_YEAR = "month_with_year",
    YEAR_ONLY = "year_only",
    BIGINT = "bigint",
    DECIMAL = "decimal",
    DOUBLE = "double",
    OBJECT = "Object",
    ARRAY = "Array",
    ARRAY_STRING = "ArrayString",
    BRANCH_CODE_FORMAT = "BranchCodeFormat",
}

export enum ResponseValidationMessageEnum {
    UUID = "InvalidUuid",
    STRING = "InvalidString",
    NUMBER = "InvalidNumber",
    BOOLEAN = "InvalidBoolean",
    EMAIL = "InvalidEmail",
    PHONE = "InvalidPhone",
    NO_SPECIAL_CHARACTERS = "InvalidNoSpecialCharacters",
    ENUM = "InvalidEnum",
    REQUIRED = "Required",
    LETTER_ONLY = "InvalidLetterOnly",
    ARRAY = "InvalidArray",
    OBJECT = "InvalidObject",
    IS_REQUIRED = "IsRequired",
    MAX_CHAR = "InvalidMaximumCharacters",
    MIN_CHAR = "InvalidMinimumCharacters",
    MIN_NUMBER = "InvalidMinimumNumber",
    MAX_NUMBER = "InvalidMaximumNumber",
    MIN_ARRAY_ELEMENT = "InvalidMinimumArrayElement",
    MAX_ARRAY_ELEMENT = "InvalidMaximumArrayElement",
    NO_PROHIBITED_CHARACTERS = "InvalidNoProhibitedCharacters",
    STRING_BOOLEAN_NUMERIC = "InvalidStringBooleanNumeric",
    STRING_OF_NUMBER_OR_FLOAT = "InvalidStringOfNumberOrFloat",
    STRING_OF_MAP_COORDINATE = "InvalidStringOfMapCoordinate",
    STRING_DATE_FORMAT = "Invalid date format (YYYY-MM-DD HH:mm:ss)",
    STRING_DATE_RANGE = "Invalid date range format (YYYY-MM-DD,YYYY-MM-DD)",
    DATE = "InvalidDate",
    DATE_ISO = "InvalidDateISO",
    DATE_ONLY = "Invalid date format (YYYY-MM-DD)",
    MONTH_WITH_YEAR = "Invalid month format (YYYY-MM)",
    YEAR_ONLY = "Invalid year format (YYYY)",
    BIGINT = "Invalid BigInt format",
    DECIMAL = "Invalid decimal format",
    DOUBLE = "Invalid double/float format",
    ARRAY_STRING = "Invalid array of string",
    BRANCH_CODE_FORMAT = "Invalid branch code format",
}

export enum ResponseValidationDuplicate {
    DUPLICATED_EMAIL = "DuplicatedEmail",
    DUPLICATED_PHONE = "DuplicatedPhone",
}
